// Ambient types for the Cloudflare Workers runtime. This file is normally
// generated by `wrangler types`; a minimal hand-written version is kept here so
// `import { env } from "cloudflare:workers"` type-checks (used by the dev-only
// page-SEO seed companion route). Regenerate with `npm run generate-types`.
declare module "cloudflare:workers" {
  export const env: {
    /** D1 binding (see wrangler.jsonc). */
    DB: import("@cloudflare/workers-types").D1Database;
    [key: string]: unknown;
  };
}
